import * as THREE from "three";
import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader.js";

export type CFStyle="versatile"|"precision"|"force"|"command";
type Pose="idle"|"light"|"heavy"|"switch"|"parry"|"dodge"|"hit"|"down"|"install";
type BoneKey="hips"|"spine"|"chest"|"neck"|"head"|"upperarm_l"|"lowerarm_l"|"hand_l"|"upperarm_r"|"lowerarm_r"|"hand_r"|"thigh_l"|"calf_l"|"foot_l"|"thigh_r"|"calf_r"|"foot_r";

const aliases:Record<BoneKey,string[]>={
 hips:["mixamorig:Hips","pelvis","root"],spine:["mixamorig:Spine1","mixamorig:Spine","spine_02","spine_01"],chest:["mixamorig:Spine2","spine_05","spine_04","spine_03"],neck:["mixamorig:Neck","neck_02","neck_01"],head:["mixamorig:Head","head"],
 upperarm_l:["mixamorig:LeftArm","upperarm_l"],lowerarm_l:["mixamorig:LeftForeArm","lowerarm_l"],hand_l:["mixamorig:LeftHand","hand_l"],upperarm_r:["mixamorig:RightArm","upperarm_r"],lowerarm_r:["mixamorig:RightForeArm","lowerarm_r"],hand_r:["mixamorig:RightHand","hand_r"],
 thigh_l:["mixamorig:LeftUpLeg","thigh_l"],calf_l:["mixamorig:LeftLeg","calf_l"],foot_l:["mixamorig:LeftFoot","foot_l"],thigh_r:["mixamorig:RightUpLeg","thigh_r"],calf_r:["mixamorig:RightLeg","calf_r"],foot_r:["mixamorig:RightFoot","foot_r"]
};

export class CharacterFrame021{
 root=new THREE.Group();visual=new THREE.Group();bones=new Map<BoneKey,THREE.Object3D>();sockets=new Map<string,THREE.Object3D>();rigLabel="UNMAPPED";ready=false;pose:Pose="idle";poseTime=0;poseDuration=0;
 private baseQuat=new Map<THREE.Object3D,THREE.Quaternion>();private props:THREE.Object3D[]=[];
 constructor(public assetUrl:string,public style:CFStyle,public targetHeight=1.85){this.root.add(this.visual)}
 async load(){
  const gltf=await new GLTFLoader().loadAsync(this.assetUrl);gltf.scene.traverse(o=>{if((o as any).isCamera||(o as any).isLight)o.visible=false;if((o as any).isMesh)(o as THREE.Mesh).frustumCulled=false});
  this.visual.add(gltf.scene);this.normalize(gltf.scene);this.map(gltf.scene);this.makeSockets();for(const b of this.bones.values())this.baseQuat.set(b,b.quaternion.clone());this.makeRoleProps();this.ready=true;return this;
 }
 private normalize(scene:THREE.Object3D){scene.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(scene),sz=new THREE.Vector3();box.getSize(sz);scene.scale.multiplyScalar(sz.y?this.targetHeight/sz.y:1);scene.updateMatrixWorld(true);const b2=new THREE.Box3().setFromObject(scene),c=new THREE.Vector3();b2.getCenter(c);scene.position.set(scene.position.x-c.x,scene.position.y-b2.min.y,scene.position.z-c.z)}
 private map(scene:THREE.Object3D){const by=new Map<string,THREE.Object3D>();scene.traverse(o=>by.set(o.name,o));(Object.keys(aliases) as BoneKey[]).forEach(k=>{for(const n of aliases[k]){const b=by.get(n);if(b){this.bones.set(k,b);break}}});this.rigLabel=by.has("mixamorig:Hips")?"MIXAMO":by.has("pelvis")?"ALPHA-41":"GENERIC"}
 private makeSockets(){const add=(name:string,key:BoneKey,pos=new THREE.Vector3())=>{const b=this.bones.get(key);if(!b)return;const s=new THREE.Object3D();s.position.copy(pos);b.add(s);this.sockets.set(name,s)};add("weapon_r","hand_r");add("weapon_l","hand_l");add("back","chest",new THREE.Vector3(0,-.04,-.12));add("head_fx","head",new THREE.Vector3(0,.12,0));add("chest_fx","chest",new THREE.Vector3(0,.08,.1));add("foot_l","foot_l");add("foot_r","foot_r")}
 socket(n:string){return this.sockets.get(n)}
 trigger(p:Pose,d=.28){if(p==="down"){this.pose="down";this.poseDuration=999;this.poseTime=0;return}this.pose=p;this.poseDuration=d;this.poseTime=0}
 recoverFromDown(){if(this.pose==="down"){this.pose="idle";this.poseTime=this.poseDuration=0}}
 private clearProps(){this.props.forEach(p=>p.removeFromParent());this.props=[]}
 setWeaponFrame(frame:string){if(this.style!=="versatile")return;this.clearProps();const s=this.socket("weapon_r");if(!s)return;let g:THREE.BufferGeometry;if(frame==="BREAKER")g=new THREE.BoxGeometry(.18,.18,1.15);else if(frame==="GUNFORM")g=new THREE.BoxGeometry(.12,.22,.62);else if(frame==="TWIN ARMS")g=new THREE.BoxGeometry(.07,.07,.72);else g=new THREE.BoxGeometry(.08,.08,1.25);const m=new THREE.MeshStandardMaterial({color:0x151922,metalness:.82,roughness:.28,emissive:0x27d7e8,emissiveIntensity:.65}),mesh=new THREE.Mesh(g,m);mesh.position.z=.48;s.add(mesh);this.props.push(mesh)}
 private makeRoleProps(){if(this.style==="versatile"){this.setWeaponFrame("BLADE");return}if(this.style==="precision"){const s=this.socket("back");if(!s)return;for(let i=0;i<3;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.045,.045,.95),new THREE.MeshStandardMaterial({color:0x1b1720,emissive:0x8d63ff,emissiveIntensity:.45}));m.position.set((i-1)*.16,.12,-.02);s.add(m);this.props.push(m)}}else if(this.style==="force"){const s=this.socket("chest_fx")||this.socket("back");if(!s)return;for(const side of [-1,1]){const m=new THREE.Mesh(new THREE.TorusGeometry(.22,.025,8,24),new THREE.MeshBasicMaterial({color:0x79d9ff,transparent:true,opacity:.72}));m.position.set(side*.55,.05,.05);m.rotation.y=Math.PI/2;s.add(m);this.props.push(m)}}else{const s=this.socket("chest_fx");if(!s)return;const m=new THREE.Mesh(new THREE.OctahedronGeometry(.09),new THREE.MeshBasicMaterial({color:0xc386ff}));m.position.set(0,.06,.16);s.add(m);this.props.push(m)}}
 update(dt:number,sig:any={}){if(!this.ready)return;this.poseTime+=dt;if(this.pose!=="idle"&&this.pose!=="down"&&this.poseTime>=this.poseDuration){this.pose="idle";this.poseTime=0}for(const [b,q] of this.baseQuat)b.quaternion.copy(q);const t=performance.now()/1000,armL=this.bones.get("upperarm_l"),armR=this.bones.get("upperarm_r"),legL=this.bones.get("thigh_l"),legR=this.bones.get("thigh_r"),ch=this.bones.get("chest"),hips=this.bones.get("hips"),head=this.bones.get("head");const add=(o:THREE.Object3D|undefined,x=0,y=0,z=0)=>{if(o)o.quaternion.multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(x,y,z)))};if(this.pose==="down"||sig.downed){add(hips,0,0,Math.PI/2);add(ch,.15);return}if(sig.moving&&this.pose==="idle"){const cad=this.style==="precision"?7.5:this.style==="force"?8.2:9,amp=this.style==="precision"?.33:this.style==="command"?.36:.55,a=Math.sin(t*cad)*amp*Math.min(1,sig.moveSpeed||0);add(armL,a);add(armR,-a);add(legL,-a*.75);add(legR,a*.75)}const k=this.poseDuration?Math.min(1,this.poseTime/this.poseDuration):0,sw=Math.sin(k*Math.PI);if(this.pose==="light"){if(this.style==="precision"){add(ch,0,-.14*sw);add(armR,-.16,-.48*sw,-.4*sw)}else if(this.style==="force"){add(ch,-.08,-.18*sw);add(armR,-.35,-.35*sw,-.6*sw);add(armL,-.25,.25*sw,.45*sw)}else if(this.style==="command"){add(ch,0,-.1*sw);add(armR,-.2,-.18,-.42*sw);add(head,0,.1*sw)}else{add(ch,0,-.28*sw);add(armR,-.25,-.75*sw,-.8*sw)}}if(this.pose==="heavy"){if(this.style==="precision"){add(ch,-.08,-.24*sw);add(armR,-.42,-.28,-.65*sw)}else if(this.style==="force"){add(ch,-.22,-.2*sw);add(armR,-.7,-.25,-.95*sw);add(armL,-.58,.22,.7*sw)}else if(this.style==="command"){add(ch,-.05,.16*sw);add(armL,-.35,.35,.35);add(armR,-.18,-.35,-.2)}else{add(ch,-.15,-.45*sw);add(armR,-.85,-.35,-1.1*sw)}}if(this.pose==="switch"){add(ch,0,.35*sw);add(armR,-.4,.15,-.5*sw)}if(this.pose==="parry"){if(this.style==="force"){add(armL,-.45,.25,.65);add(armR,-.45,-.25,-.65)}else if(this.style==="command"){add(armL,-.28,.12,.45);add(armR,-.18,-.08,-.22)}else{add(armR,-.45,-.15,-.7)}}if(this.pose==="dodge"){add(ch,.28,0,.15*Math.sin(k*Math.PI*2));add(hips,.12)}if(this.pose==="hit"){add(ch,.22,0,.22)}if(this.pose==="install"||sig.install){add(ch,-.08);add(armL,-.35,0,.35);add(armR,-.35,0,-.35)}}
}
